--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26/04/2015 14:02:44
-- Server version: 5.1.44-community
-- Client version: 4.1
--


--
-- Definition for database faci_rpg
--
DROP DATABASE IF EXISTS faci_rpg;
CREATE DATABASE faci_rpg
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE faci_rpg;

--
-- Definition for table desvantagens
--
CREATE TABLE desvantagens (
  desv_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  desv_nome VARCHAR(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  desv_descricao VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  desv_preco INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (desv_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table fotos_npc
--
CREATE TABLE fotos_npc (
  ftNpc_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ftNpc_npcId INT(10) UNSIGNED DEFAULT NULL,
  ftNpc_imagem BLOB DEFAULT NULL,
  PRIMARY KEY (ftNpc_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table fotos_personagem
--
CREATE TABLE fotos_personagem (
  ftp_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ftp_imagem BLOB DEFAULT NULL,
  PRIMARY KEY (ftp_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table loja
--
CREATE TABLE loja (
  prod_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  prod_nome VARCHAR(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  prod_preco INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (prod_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table usuario
--
CREATE TABLE usuario (
  user_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_login VARCHAR(20) NOT NULL,
  user_senha VARCHAR(10) NOT NULL,
  user_tipoJogador VARCHAR(45) NOT NULL,
  PRIMARY KEY (user_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table vantagens
--
CREATE TABLE vantagens (
  vant_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  vant_nome VARCHAR(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  vant_descricao VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  vant_preco INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (vant_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table mestre
--
CREATE TABLE mestre (
  mestre_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  mestre_nome VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  mestre_userId INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (mestre_ID),
  CONSTRAINT FK_mestre_usuario_user_ID FOREIGN KEY (mestre_userId)
    REFERENCES usuario(user_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table campanha
--
CREATE TABLE campanha (
  camp_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  camp_nome VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  camp_historia TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  camp_tipoJogo VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  camp_mestreId INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (camp_ID),
  CONSTRAINT FK_campanha_mestre_mestre_ID FOREIGN KEY (camp_mestreId)
    REFERENCES mestre(mestre_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table npc
--
CREATE TABLE npc (
  npc_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  npc_nome VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  npc_forca INT(11) UNSIGNED DEFAULT NULL,
  npc_habilidade INT(11) UNSIGNED DEFAULT NULL,
  npc_resistencia INT(11) UNSIGNED DEFAULT NULL,
  npc_armadura INT(11) UNSIGNED DEFAULT NULL,
  npc_poderFogo INT(11) UNSIGNED DEFAULT NULL,
  npc_pontosVida INT(11) UNSIGNED DEFAULT NULL,
  npc_pontosMagia INT(11) UNSIGNED DEFAULT NULL,
  npc_campId INT(10) UNSIGNED DEFAULT NULL,
  npc_fotoId INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (npc_ID),
  CONSTRAINT FK_npc_campanha_camp_ID FOREIGN KEY (npc_campId)
    REFERENCES campanha(camp_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_npc_fotos_personagem_ftp_ID FOREIGN KEY (npc_fotoId)
    REFERENCES fotos_personagem(ftp_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'personagem controlado pelo mestre';

--
-- Definition for table personagem
--
CREATE TABLE personagem (
  person_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  person_nome VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  person_forca INT(10) UNSIGNED DEFAULT NULL,
  person_habilidade INT(10) UNSIGNED DEFAULT NULL,
  person_resistencia INT(10) UNSIGNED DEFAULT NULL,
  person_armadura INT(10) UNSIGNED DEFAULT NULL,
  person_poderFogo INT(10) UNSIGNED DEFAULT NULL,
  person_pontosVida INT(10) UNSIGNED DEFAULT 0,
  person_pontosMagia INT(10) UNSIGNED DEFAULT 0,
  person_XP INT(10) UNSIGNED DEFAULT 0,
  person_pontosJogador INT(10) UNSIGNED DEFAULT 12,
  person_campId INT(10) UNSIGNED DEFAULT NULL,
  person_fotoId INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (person_ID),
  CONSTRAINT FK_personagem_campanha_camp_ID FOREIGN KEY (person_campId)
    REFERENCES campanha(camp_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_personagem_fotos_personagem_ftp_ID FOREIGN KEY (person_fotoId)
    REFERENCES fotos_personagem(ftp_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table anexar_desvantagem
--
CREATE TABLE anexar_desvantagem (
  anDesv_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  anDesv_desvId INT(10) UNSIGNED DEFAULT NULL,
  anDesv_personId INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (anDesv_ID),
  CONSTRAINT FK_anexar_desvantagem_desvantagens_desv_ID FOREIGN KEY (anDesv_desvId)
    REFERENCES desvantagens(desv_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_anexar_desvantagem_personagem_person_ID FOREIGN KEY (anDesv_personId)
    REFERENCES personagem(person_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table anexar_vantagem
--
CREATE TABLE anexar_vantagem (
  anVant_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  anVant_vantId INT(10) UNSIGNED DEFAULT NULL,
  anVant_personId INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (anVant_ID),
  CONSTRAINT FK_anexar_vantagem_personagem_person_ID FOREIGN KEY (anVant_personId)
    REFERENCES personagem(person_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_anexar_vantagem_vantagens_vant_ID FOREIGN KEY (anVant_vantId)
    REFERENCES vantagens(vant_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;